## • Introduction :

#### Say "Hello, World!" With Python

In [ ]:
if __name__ == '__main__':
    print("Hello, World!")

#### Python If-Else

In [ ]:
import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input().strip())
    if n%2 != 0:
        print("Weird")
    else:
        if n in range(2,6):
            print("Not Weird")
        elif n in range(6,21):
            print("Weird")
        else:
            print("Not Weird")

#### Arithmetic Operators

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

#### Python: Division

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

#### Loops

In [ ]:
if __name__ == '__main__':
    n = int(input())
    for x in range(n):
        print(x**2)

#### Write a function

In [96]:
def is_leap(year):         
    
    leap = False
    
    y4 = year/4
    y400 = year/400
    y100 = year/100
    if y100.is_integer() and y400.is_integer():
        leap = True
    elif y4.is_integer() and not y100.is_integer() :
        leap = True 
    return leap

year = int(input())
print(is_leap(year))

1900
False


#### Print Function

In [17]:
if __name__ == '__main__':
    n = int(input())
    def print_string():
        for x in range(1, n+1, 1):
            print(x, end = "")
    print_string()

3
123

## • Data types:

#### List Comprehensions

In [ ]:
if __name__ == '__main__':
    L = [] 
    
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    
    L = [[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1)]
    L = [element for element in L if sum(element) != n]
    print(L, " -> lenght = ", len(L))

#### Tuples

In [ ]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t = ()
    for x in integer_list:
        t = t + (x, )  # add item to the tuple
    print(t)
    print(hash(t))

#### Nested Lists

In [ ]:
if __name__ == '__main__':
    big_list = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        nested_list = [name, score]
        big_list.append(nested_list)
    #print(big_list)
    
    big_list.sort( key = lambda x: (x[1], x[0]))  #sorting by double criteria
    #print(big_list)
    
    lowest = big_list[0][1]
    big_list = [x for x in big_list if x[1] != lowest]
    #print(big_list)
    second_lowest = big_list[0][1]
    big_list = [x for x in big_list if x[1] == second_lowest]
    #print(big_list)
    
    for x in big_list:
        print(x[0])

#### Finding the percentage

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    #print(student_marks)
    
    query_name = input()
    average = sum(student_marks[query_name])/len(student_marks[query_name])
    
    print("{:.2f}".format(average))

#### Find the Runner-Up Score!

In [ ]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    scores = [x for x in arr]
    
    scores = [x for x in scores if x != max(scores)]
    print(max(scores))

#### Lists

In [ ]:
if __name__ == '__main__':
    
    N = int(input())
    l = []
    
    for x in range(N):
        query = (input().split())
        #print(query, len(query))
        
        if len(query)==2 and query[0] == "remove":
            l.remove(int(query[1]))
        elif len(query)==2 and query[0] == "append":
            l.append(int(query[1]))
        elif len(query)==3 and query[0] == "insert":
            l.insert(int(query[1]),int(query[2]))
        elif len(query) == 1 and query[0] == "sort":
            l.sort()
        elif len(query) == 1 and query[0] == "pop":
            l.pop()
        elif len(query) == 1 and query[0] == "reverse":
            l.reverse()
        elif len(query) == 1 and query[0] == "print":
            print(l)

## • Strings:

#### sWAP cASE

In [303]:
def swap_case(s):
    s = s.swapcase()
    return s

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


#### What's Your Name?

In [ ]:
# Complete the 'print_full_name' function below.

# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last

def print_full_name(first, last):
    # Write your code here
    s = "Hello {} {}! You just delved into python.".format(first, last)
    print(s)

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

#### String Split and Join

In [314]:
def split_and_join(line):
    # write your code here
    line = line.split(" ")
    line = "-".join(line)
    return line

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

questa è una stringa di prova per vedere se funziona
questa-è-una-stringa-di-prova-per-vedere-se-funziona


#### Mutations

In [321]:
def mutate_string(string, position, character):
    string = string[:position] + str(character) + string[position+1:]
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 K
abracKdabra


#### Find a string

In [82]:
def count_substring(string, sub_string):
    count = 0
    for i in range(0, len(string)):  
        if (string[i:i+len(sub_string)]) == sub_string:
            count += 1
    return count
    
if __name__ == '__main__':
    
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


#### Text Wrap

In [ ]:
import textwrap

def wrap(string, max_width):
    blocks = (textwrap.wrap(string, max_width))
    blocks = "\n".join(blocks)
    return blocks

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

#### Text Alignment

In [1]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))
    
#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))
    

3
  H  
 HHH 
HHHHH
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
 HHHHHHHHHHHHHHH  
 HHHHHHHHHHHHHHH  
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
 HHH         HHH        
            HHHHH 
             HHH  
              H   


#### String Validators:

In [ ]:
if __name__ == '__main__':      # I have looked how to use any() on https://realpython.com/any-python
    s = input()
    if any(map(str.isalnum, s)) == True:
        print("True")
    else:
        print("False")
    if any(map(str.isalpha, s)) == True:
        print("True")
    else:
        print("False")
    if any(map(str.isdigit, s)) == True:
        print("True")
    else:
        print("False")
    if any(map(str.islower, s)) == True:
        print("True")
    else:
        print("False")
    if any(map(str.isupper, s)) == True:
        print("True")
    else:
        print("False")       

#### Designer Door Mat

In [93]:
N,M = map(int,input().split())
block = ".|."

13 39


In [94]:
for i in range(N//2):
    print(((2*i+1)*block).center(M,'-'))
    
print('WELCOME'.center(M,'-'))

for i in range((N//2)):
    print((((N-2)-(2*i))*block).center(M,'-'))

------------------.|.------------------
---------------.|..|..|.---------------
------------.|..|..|..|..|.------------
---------.|..|..|..|..|..|..|.---------
------.|..|..|..|..|..|..|..|..|.------
---.|..|..|..|..|..|..|..|..|..|..|.---
----------------WELCOME----------------
---.|..|..|..|..|..|..|..|..|..|..|.---
------.|..|..|..|..|..|..|..|..|.------
---------.|..|..|..|..|..|..|.---------
------------.|..|..|..|..|.------------
---------------.|..|..|.---------------
------------------.|.------------------


#### String Formatting

In [ ]:
def print_formatted(number):
    # your code goes here
    for x in range(1, n+1):
        print(str(x).rjust(space, " "), 
          oct(x)[2:].rjust(space, " "), 
          hex(x)[2:].rjust(space, " ").upper(), 
          bin(x)[2:].rjust(space, " "))
    
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

#### Capitalize!

In [227]:
def solve(s):
    parts = list(s)
    #print(parts)
    for i in range(len(parts)):
        if parts[i] == " ":
            parts[i+1] = parts[i+1].upper() #maiuscola dopo lo spazio
    parts[0] = parts[0].upper()
    #print(parts)
    name = "".join(parts)
    #print(name)
    return name

solve("chris alan")

'Chris Alan'

## • Sets:

#### Introduction to Sets

In [ ]:
def average(array):
    # your code goes here
    array = set(array)
    result = sum(array)/len(array)
    return result

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

#### Set . add ( )

In [ ]:
arr = set()
n = int(input())
for i in range(n):
    country = str(input())
    arr.add(country)
print(len(arr))

#### Symmetric Difference

In [ ]:
M = int(input())
arr_M = set(map(int, input().split()))

N = int(input())
arr_N = set(map(int, input().split()))

result = sorted ( arr_N.union(arr_M) - arr_N.intersection(arr_M) )

print(*result, sep="\n")

#### Set . union ( ) Operation

In [ ]:
n = int(input())
arr_english = set(map(int, input().split()))

b = int(input())
arr_french = set(map(int, input().split()))

result = arr_english.union(arr_french)
print(len(result))

#### Set . intersection ( ) Operation

In [ ]:
n = int(input())
arr_english = set(map(int, input().split()))

b = int(input())
arr_french = set(map(int, input().split()))

result = arr_english.intersection(arr_french)
print(len(result))

#### Set . difference ( ) Operation

In [ ]:
n = int(input())
arr_english = set(map(int, input().split()))

b = int(input())
arr_french = set(map(int, input().split()))

result = arr_english.difference(arr_french)
print(len(result))

#### Set . symmetric_difference ( ) Operation

In [ ]:
n = int(input())
arr_english = set(map(int, input().split()))

b = int(input())
arr_french = set(map(int, input().split()))

result = arr_english.symmetric_difference(arr_french)
print(len(result))

#### Set .discard( ), .remove( ) & .pop( )

In [ ]:
n = int(input())
s = set(map(int, input().split()))

N = int(input())

for x in range(N):
    query = (input().split())
    #print(query, len(query))
    if len(query)==2 and query[0] == "remove":
        s.remove(int(query[1]))
    elif len(query)==2 and query[0] == "discard":
        s.discard(int(query[1]))
    elif len(query) == 1:
        s.pop()
        
print(sum(s))

#### Set Mutations

In [ ]:
lenght_A = int(input())
A = set(map(int, input().split()))
N = int(input())

for i in range(N):
    query = (input().split())
    other_set = set(map(int, input().split()))
    if query[0] == "update":
        A.update(other_set)
        #print("Set A = ", A , sum(A))
    if query[0] == "intersection_update":
        A.intersection_update(other_set)
        #print("Set A = ", A, sum(A))
    if query[0] == "difference_update":
        A.difference_update(other_set)
        #print("Set A = ", A, sum(A))
    if query[0] == "symmetric_difference_update":
        A.symmetric_difference_update(other_set)
        #print("Set A = ", A, sum(A))
        
print(sum(A))
    

#### Check Subset

In [ ]:
test_cases = int(input())
for x in range(test_cases):
    
    lenght_A = int(input())
    A = set(map(int, input().split()))
    lenght_B = int(input())
    B = set(map(int, input().split()))
    
    print(A.issubset(B))

#### Check Strict Superset

In [ ]:
A = set(map(int, input().split()))
n = int(input())
s_tot = set ()
for x in range(n):
    other_set = set(map(int, input().split()))
    s_tot = s_tot.union(other_set)
print(A.issuperset(s_tot))

#### The Captain's Room

In [186]:
k = int(input())
room_number_list = sorted ( list(map(int, input().split())) )
#print(room_number_list)

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 
[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 8]


In [188]:
for i in range(len(room_number_list)):
    if i != len(room_number_list)-1:
        if room_number_list[i] != room_number_list[i+1] and room_number_list[i] != room_number_list[i-1]:
            print(room_number_list[i])
            
    else:
        print(room_number_list[i])

8


## • Collections:

#### collections.Counter ( )

In [ ]:
# with Counter
from collections import Counter

n_shoes = int(input())
shoes =  list(map(int, input().split()))
n_costumers = int(input())
profit = 0

c = Counter(shoes)

for x in range(n_costumers):
    request = (input().split())
    
    if int(request[0]) in c.keys() and c[int(request[0])] > 0 :
        profit += int(request[1])
        c[int(request[0])] -= 1
        
print(profit)  

In [ ]:
# without Counter

n_shoes = int(input())
shoes =  list(map(int, input().split()))
n_costumers = int(input())
profit = 0
for x in range(n_costumers):
    request = (input().split())
    
    if int(request[0]) in shoes:
        profit += int(request[1])
        shoes.remove(int(request[0]))
        
print(profit)

#### Collections .namedtuple( )

In [ ]:
from collections import namedtuple

N = int(input())
data = namedtuple('data',input())
marks_list = []
for i in range(N):
    marks = int(data(*input().split()).MARKS)
    marks_list.append(marks)

result = sum(marks_list)/N
print(result)

#### Collections .OrderedDict( )

In [ ]:
from collections import OrderedDict

N = int(input())
ordered_dictionary = OrderedDict()
for x in range(N):
    elenco = input().rsplit(' ', 1)
    if elenco [0] in ordered_dictionary:
        ordered_dictionary[elenco[0]] += int(elenco[1])
    else:
        ordered_dictionary[elenco[0]] = int(elenco[1])
        
for i in ordered_dictionary:
    print (i, ordered_dictionary[i])

#### Collections .deque( )

In [ ]:
from collections import deque

N = int(input())
d = deque()

for x in range(N):
    query = (input().split())
        #print(query, len(query))
        
    if query[0] == "append":
        d.append(int(query[1]))
            
    elif query[0] == "appendleft":
        d.appendleft(int(query[1]))
            
    elif query[0] == "pop":
        d.pop()
                
    elif query[0] == "popleft":
        d.popleft()
print(*d)

#### DefaultDict Tutorial

In [ ]:
from collections import defaultdict

d = defaultdict(list)
n, m = map(int,input().split())

for i in range(1, n+1):
    insert = str(input())
    
    d[insert].append(str(i))


for i in range(m):
    b = input()
    
    if b in d: 
        print(' '.join(d[b]))
    else: 
        print(-1)

## • Date and Time:

#### Calendar Module

In [51]:
from datetime import date
import calendar

data = input()
data = datetime.strptime(data, '%m %d %Y')

print ( calendar.day_name[data.weekday()].upper() )

08 05 2015
WEDNESDAY


In [58]:
import calendar
MM, DD, YYYY = map(int, input().split())
print ( (calendar.day_name)[calendar.weekday(YYYY, MM, DD)].upper())

08 05 2015
WEDNESDAY


#### Time Delta

In [ ]:
from datetime import datetime

# Complete the time_delta function below.

def time_delta(t1, t2):
    converter = "%a %d %b %Y %H:%M:%S %z"
    time1 = datetime.strptime (t1, converter)
    time2 = datetime.strptime (t2, converter)
    result = abs(time1-time2).total_seconds()
    return result
    
    
if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        t1 = input()
        t2 = input()
        delta = time_delta(t1, t2)
        
        print(int(delta))


## • Errors and Exceptions:

#### Exceptions

In [ ]:
T = int(input())

for x in range(T):
    try:
        a, b  = map(int, input().split())
        print(a//b)
        
    except (ValueError, ZeroDivisionError) as e:
        print ("Error Code:", e)

## • Built-ins:

#### Zipped!

In [ ]:
N, X = map(int, input().split())
marks_list = []

for i in range(X):
    marks = list(map(float, input().split()))
    marks_list.append(marks)
    
result = [sum(i)/len(i) for i in zip(*marks_list)]
print(*result, sep="\n")

#### ginortS

In [278]:
s = str(input())

digits_dispari = []
digits_pari = []
lower= []
upper = []

Sorting1234


In [279]:
for i in range(len(s)):

    if s[i].isdigit() and int(s[i])%2 == 0:
        digits_pari.append(s[i])
    elif s[i].isdigit() and int(s[i])%2 != 0:
        digits_dispari.append(s[i])
    elif s[i].isupper():
        upper.append(s[i])
    elif s[i].islower():
        lower.append(s[i])

result = sorted(lower) + sorted(upper) + sorted(digits_dispari) +sorted(digits_pari)
result = ''.join(result)
print(result)

ginortS1324


#### Athlete Sort

In [ ]:

if __name__ == '__main__':
    
    first_multiple_input = input().rstrip().split()

    n, m = int(first_multiple_input[0]), int(first_multiple_input[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))
        
    #print(*arr)
    k = int(input().strip())

    result = (sorted(arr, key = lambda x: x[k]))
    for x in result:
        print(*x)

## • XML:

#### XML 1 - Find the Score:

In [61]:
def get_attr_number(node):
    
    # your code goes here
    
    result = 0
    for x in node.iter():
        #print(x)
        #print(x.attrib)
        result += len(x.attrib)
        
    return result

#### XML 2 - Find the Maximum Depth:

In [66]:
maxdepth = 0

def depth(elem, level):
    global maxdepth
    # your code goes here
    
    if level == maxdepth :
        maxdepth += 1
    for i in elem:
        depth(i, level+1)
    
### Solution understood thanks to YouTube

## • Closures and Decorations :

#### Standardize Mobile Number Using Decorators

In [ ]:
def wrapper(f):
    def fun(l):
        # complete the function
        
        for i in range(len(l)):
            prefix = "+91 "
            if len(l[i]) != 10:
                l[i] = l[i][-10:]

            block2 = l[i][-5:]
            block1 = l[i][:-5]
            l[i] = prefix + block1 + " " + block2
        print(*sorted(l), sep="\n")
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

#### Decorators 2 - Name Directory

In [346]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        result = map(f, sorted(people, key=lambda x: int(x[2])))
        return result
        
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Andria Bustle 30 F
Robert Bustle 32 M
Mike Thomson 20 M
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


## • Python Functionals :

#### Map and Lambda Function:

In [163]:
cube  = lambda x: x**3 # complete the lambda function 

def fibonacci(n):
    fib = [0,1]
    if n == 0:
        fib = []
    elif n == 1:
        fib.pop()
    else:
        for i in range(2, n):
            fib.append(fib[i-1] + fib[i-2] )
    return fib

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


## • Numpy :

#### Arrays

In [1]:
import numpy

def arrays(arr):
    # complete this function
    arr = numpy.array(arr,float)
    reversed_arr = arr[::-1]
    #print (b)
    return reversed_arr
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


#### Shape and Reshape

In [3]:
arr = input().strip().split(' ')
arr = numpy.array(arr, int)
reshaped = numpy.reshape(arr,(3,3))
print (reshaped)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Concatenate

In [ ]:
#import numpy

N, M, P = map(int,input().split())

arr_n = [(input().split()) for i in range(N)]
np_n = numpy.array(arr_n, int)
arr_m = [input().split() for i in range(M)]
np_m = numpy.array(arr_m, int)
tot_arr = numpy.concatenate((np_n, np_m), axis = 0)
print(tot_arr)

#### Transpose and Flatten

In [122]:
N, M = map(int,input().split())
arr_n = numpy.array( [input().split() for i in range(N)], int)

print (numpy.transpose(arr_n))
print(arr_n.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#### Zeros and Ones

In [137]:
dimensions = tuple(map(int,input().split()))

print (numpy.zeros((dimensions),dtype = int))  
print (numpy.ones((dimensions),dtype = int))  

3 3 3


#### Eye and Identity

In [158]:
numpy.set_printoptions(legacy = "1.13")

n, m = map(int,input().split())

print(numpy.eye(n, m, k = 0))

5 7
[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]]


#### Dot and Cross

In [ ]:
N = int(input())
arr_n = numpy.array( [input().split() for i in range(N)], int)
arr_m = numpy.array( [input().split() for i in range(N)], int)

result = numpy.dot(arr_n, arr_m)
print(result)

#### Min and Max

In [177]:
N, M = map(int,input().split())
arr_n = numpy.array( [input().split() for i in range(N)], int)
result = numpy.min(arr_n, axis = 1)

print(max(result))

4 2
2 5
3 7
1 3
4 0
3


#### Inner and Outer

In [ ]:
arr1 = numpy.array(input().strip().split(), int)
arr2 = numpy.array(input().strip().split(), int)

print (numpy.inner(arr1, arr2))
print (numpy.outer(arr1, arr2))

#### Sum and Prod

In [193]:
N, M = map(int,input().split())

matrix = numpy.array([input().split() for i in range(N)], int)

result = numpy.sum(matrix, axis = 0)
#print(result)
print (numpy.prod(result))


3 3
1 1 1
1 1 1
1 1 1
27


#### Polynomials

In [12]:
#import numpy

poly_coefs = list(map(float,input().split()))
x = float(input())

result = numpy.polyval(poly_coefs , x)

print(result)

1.1 2 3
0
3.0


#### Floor, Ceil and Rint

In [17]:
numpy.set_printoptions(legacy = "1.13")

arr = numpy.array(input().strip().split(), float)

#print(arr)
print (numpy.floor(arr))
print (numpy.ceil(arr))
print (numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


#### Array Mathematics

In [29]:
N, M = map(int,input().split())

arr_A = numpy.array([input().split() for i in range(N)], int)
arr_B = numpy.array([input().split() for i in range(N)], int)

print(arr_A + arr_B)
print(arr_A - arr_B)
print(arr_A * arr_B)
print(arr_A // arr_B)
print(arr_A % arr_B)
print(arr_A ** arr_B)

1 4
1 2 3 4
5 6 7 8


#### Linear Algebra

In [53]:
numpy.set_printoptions(legacy='1.13')

N = int(input())
matrix = numpy.array([input().split() for i in range(N)], float)

result = numpy.linalg.det(matrix)
print (result)

2
1.1 1.1
1.1 1.2
0.11


#### Mean, Var, and Std

In [ ]:
N, M = map(int,input().split())
matrix = numpy.array([input().split() for i in range(N)], float)

print ( numpy.mean(matrix, axis = 1) )
print ( numpy.var(matrix, axis = 0) )
print( round (numpy.std(matrix, axis = None), 11))

## • Regex and Parsing :

In [ ]:
## Some of the exercises in this section have been solved with help of the solutions found online.
## I had never worked with regular expressions before and I found them quite complicated.
## However, in any case, trying to understand the request of the exercise and the procedure to get the relative solution.

#### Re. split ( )

In [6]:
import re

regex_pattern = r"[,.]"   # Do not delete 'r'.

print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


#### Re. findall ( ) & Re. finditer ( )

In [38]:
my_stringa = "rabcdeefgyYhFjkIoomnpOeorteeeeet"

In [54]:
my_stringa = str(input())

vocali = "aeiou"
consonanti = "qwrtypsdfghjklzxcvbnm."

#re.findall(pattern, s, flag=re.IGNORECASE)
l = re.findall(r"(?<=[%s])([%s]{2,})[%s]" % (consonanti, vocali, consonanti), my_stringa, flags = re.IGNORECASE)

# ?<= Lookbehind assertion
# in pattern -> (cons)(voc)(cons)

if len(l) != 0:
    print(*l, sep="\n")
else:
    print(-1)

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


#### Re. start ( ) & Re. end ( )

In [84]:

my_stringa = str(input())

k = str(input())

pattern = re.compile(k)
m = pattern.search(my_stringa)
if not m:
    print("(-1, -1)")
else:
    while m:
        print("({0}, {1})".format(m.start(), m.end() - 1))
        m = pattern.search(my_stringa, m.start() + 1)

(0, 1)
(1, 2)
(4, 5)


#### Validating phone numbers

In [2]:
import re

In [3]:
N = int(input())

numbers = [str(input()) for i in range(N)]

pattern = re.compile(r"^[789]{1}\d{9}$")

for i in numbers:
    
    matches = list(pattern.finditer(i))
    if len(matches) != 0:
        print("YES")
    else: print("NO")

2
1252478965
9587456281
NO
YES


#### Validating Roman Numerals

In [15]:
regex_pattern = (r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$")
# Do not delete 'r'

import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


#### Detect Floating Point Number

In [ ]:
T = int(input())

pattern = re.compile(r"^([-\+])?\d{0,}\.\d{0,}$")

test_list = [str(input()) for x in range(T)]

for x in range(len(test_list)):
    
    print(str(bool(re.match(pattern, test_list[x]))))

#### Validating and Parsing Email Addresses

In [9]:
import re
import email.utils

n = int(input())

pattern = r"<[A-Za-z](\w|-|\.|_)+@[A-Za-z]+\.[A-Za-z]{1,3}>"
for i in range(n):
    name, email = str(input()).split()
    result = re.match(pattern, email)
    if result:
        print (name, email)
    

2
VIRUS <virus!@variable.:p>
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>


#### Group(), Groups() & Groupdict()

In [14]:
stringa = str(input())

pattern = r"([a-z A-Z0-9])\1"

result = re.search(pattern, stringa)
if result:
    print(result.groups()[0])
else: print("-1")

..12345678910111213141516171820212223
1


#### Hex Color Code

In [ ]:
#import re

N=int(input())

pattern = r'#[a-fA-F0-9]{3,6}'

for i in range(0,N):
    s=input()

    x=s.split()

    if len(x)>1  and  '{' not in x:
        result = re.findall( pattern , s)
        [print(i) for  i in result]

#### HTML Parser - Part 1

In [29]:
#pip install HTMLParser
from html.parser import HTMLParser

In [ ]:
# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    
    def handle_starttag(self, tag, attrs):
        print ("Start :", tag)
        
        if len(attrs) != 0:
            for i in range(len(attrs)):
                print("->", attrs[i][0], ">", attrs[i][1])
                
    def handle_endtag(self, tag):
        print ("End   :", tag)
        
    def handle_startendtag(self, tag, attrs):
        print ("Empty :", tag)
        
        if len(attrs) != 0:
            for i in range(len(attrs)):
                print("->", attrs[i][0], ">", attrs[i][1])
                
# instantiate the parser and fed it some HTML
n = int(input())
html = ""

for i in range(n):
    text = str(input())
    html += text
parser = MyHTMLParser()
parser.feed(html)

#### HTML Parser - Part 2

In [ ]:
#from html.parser import HTMLParser     # exercise completed with the help of solutions proposed online

class MyHTMLParser(HTMLParser):
    
    def handle_comment(self,data):
        char = "\n"
        if char in data:
            print(">>> Multi-line Comment")
        else:
            print(">>> Single-line Comment")
        print(data)
    def handle_data(self,data):
        if(data != '\n'):
            print(">>> Data")
            print(data) 

html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()   

#### Detect HTML Tags, Attributes and Attribute Values

In [ ]:
class MyHTMLParser(HTMLParser):
    
    def handle_starttag(self, tag, attrs):
        print (tag)
        
        if len(attrs) != 0:
            for i in range(len(attrs)):
                print("->", attrs[i][0], ">", attrs[i][1])

    def handle_startendtag(self, tag, attrs):
        print (tag)
        
        if len(attrs) != 0:
            for i in range(len(attrs)):
                print("->", attrs[i][0], ">", attrs[i][1])

n = int(input())
html = ""

for i in range(n):
    text = str(input())
    html += text
parser = MyHTMLParser()
parser.feed(html)

#### Validating UID:

In [156]:
n = int(input())
uid_to_check = []

def valid_uid(uid):
    
    uppercase = re.findall(r"[A-Z]", uid)
    digits = re.findall(r"[0-9]", uid)
    result = re.match(r"[A-Za-z0-9]{10}$", uid)
    
    if len(uppercase) < 2 or len(digits) < 3 or len(set(uid)) != len(uid) or result == None :
        print("Invalid")
    else:
        print("Valid")

for i in range(n):
    uid = str(input())
    uid_to_check.append(uid)

for i in uid_to_check:
    valid_uid(i)

## Problem 2:

In [ ]:
## I had hard times completing the exercises in this section due to the RunningTime Error. 
## Therefore to be able to deliver them, I made use of some suggestions from the web.

#### Birthday Cake Candles

In [ ]:
def birthdayCakeCandles(candles):
    
    counter = 0
    primo = candles[0]
    
    ## to find the max
    for i in (range(1,len(candles))):
        if candles[i]> primo:
            primo = candles[i]
            
    #to see how many max there are
    for i in (range(len(candles))):
        if candles[i] == primo:
            counter += 1
    return counter

if __name__ == '__main__':

    candles_count = int(input().strip())
    candles = list(map(int, input().rstrip().split()))
    result = birthdayCakeCandles(candles)
    print(result)

#### Number Line Jumps (Kangaroo)

In [ ]:
def kangaroo(x1, v1, x2, v2):
    # Write your code here
    
    not_exist = True
    while not_exist:
        x1 += v1
        x2 += v2
        if x1 == x2:
            not_exist = False
            break
        if (v1 > v2 and x1 > x2) or (v2 > v1 and x2 > x1) or (v2 == v1 and x2 != x1):
            break
        
    if not_exist:
        return'NO'
    else:
        return'YES'
    
if __name__ == '__main__':

    first_multiple_input = input().rstrip().split()
    
    x1 = int(first_multiple_input[0])
    v1 = int(first_multiple_input[1])
    x2 = int(first_multiple_input[2])
    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)
    print(result)

#### Viral Advertising

In [ ]:
def viralAdvertising(n):
    # Write your code here
    
    i = 1
    shared = 5
    liked = shared//2
    cumulative=liked
    #print(shared, liked, cumulative)
    
    while i<n:
        shared = liked*3
        liked = shared//2
        cumulative += liked
        #print(shared, liked, cumulative)
        i += 1
    return cumulative
    

if __name__ == '__main__':

    n = int(input().strip())
    result = viralAdvertising(n)
    print(result)

#### Recursive Digit Sum

In [ ]:
def super_digit(n, k):
    digits = map(int, list(n))
    digits = sum(digits)
    return get_super_digit(str(digits * k))

def get_super_digit(p):
    if len(p) == 1:
        return int(p)
    else:
        digits = map(int, list(p))
        return get_super_digit(str(sum(digits)))


if __name__ == '__main__':
    
    first_multiple_input = input().rstrip().split()
    n = first_multiple_input[0]
    k = int(first_multiple_input[1])

    result = super_digit(n, k)
    print(result)


#### Insertion Sort - Part 1

In [ ]:
def insertionSort1(n, arr):
    # Write your code here
    #print("**************************")
    
    ultimo = arr[-1]
    j = (n-2)
    
    while j >= 0 and arr[j] > ultimo:
        arr[j+1] = arr[j]
        print(*arr)
        j -= 1
    arr[j+1] = ultimo
    print(*arr)
    
if __name__ == '__main__':
    
    n = int(input().strip())
    arr = list(map(int, input().rstrip().split()))
    insertionSort1(n, arr)